#
# ~/.config/bash.d/bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

export PATH="$PATH:$HOME/.local/bin:$PATH"
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /home/kautsaralbana/.local/lib/python3.8/site-packages/powerline/bindings/bash/powerline.sh

source /home/kautsaralbana/.config/bash.d/git-prompt.sh
source /home/kautsaralbana/.config/bash.d/git-completion.bash

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '
